### ISSUE TITLE
Remove case sensitivity of properties

### ISSUE THREAD

**Issue by Az779** [decaf-dev/obsidian-vault-explorer#315]
My URL properties are part lowercase "url" and part uppercase "URL", but the Custom properties dropdown menu **only has the lowercase** one, and the selection **doesn't take effect on the uppercase URL properties**( without URL displayed in Explorer page).

![image](https://github.com/user-attachments/assets/4bdef5bd-1744-4d3d-9ae5-08f84eebc9ca)

If possible, please **remove the case sensitivity of the properties**, or make them case-sensitive in the dropdown menu.

**Comment by decaf-dev** [comment]
Hi @Az779. Thanks for the bug report.

After a little investigation, it appears that this is a feature of Obsidian, not Vault Explorer. If you open the right sidebar and click "All Properties", you should see that there is only a single, lowercase entry for `URL` and `url` properties.

Considering that Obsidian has chosen to process frontmatter in this manner, I don't see a big reason to do so otherwise in the plugin.
